// Generated by CoffeeScript 1.9.2
requirejs.config({
  paths: {
    'angular': '../build/lib/angular-route-animate.min',
    'jquery': '../build/lib/jquery.min',
    'bootstrap': '../build/lib/bootstrap.min'
  },
  shim: {
    'angular': {
      exports: 'angular'
    },
    'bootstrap': {
      deps: ['jquery'],
      exports: 'bootstrap'
    }
  }
});

requirejs(['jquery', 'angular', 'bootstrap'], function($, angular) {

  /*skel配置项
  skelparam = 
      containers: 1140
      breakpoints:
          medium: 
              media: '(min-width: 769px) and (max-width: 1200px)'
              containers: '90%'
          small:
              media: '(max-width: 768px)'
              containers: '95%'
      
  skel.init skelparam
   */
  var app;
  angular.element(document).ready(function() {
    return setTimeout(function() {
      return angular.bootstrap(document, ['myblog']);
    });
  });
  app = angular.module('myblog', ["ngRoute", "ngAnimate"]);
  app.config([
    '$routeProvider', '$locationProvider', function($routeProvider, $locationProvider) {
      return $routeProvider.when("/", {
        templateUrl: '/template/page-main.html'
      }).when("/cv", {
        templateUrl: '/template/page-cv.html'
      }).when("/contact", {
        templateUrl: '/template/page-msg.html'
      }).when("/project", {
        templateUrl: '/template/page-project.html'
      }).when("/blog", {
        templateUrl: '/template/page-blog.html'
      }).otherwise({
        redirectTo: "/"
      });
    }
  ]);
  app.factory('AuthService', [
    '$http', function($http) {
      var fn;
      fn = {};
      return {};
    }
  ]);
  app.directive('cover', function() {
    return {
      restrict: 'EA',
      link: function(scope, element, attrs) {
        var cover;
        cover = function() {
          var eh, ew, wh, ww;
          element = $(element);
          ew = element.width();
          ww = $(window).width();
          eh = element.height();
          wh = $(window).height();
          element.css('min-width', wh * ew / eh + 'px');
          if (wh === eh) {
            return element.css('left', '-' + (ew - ww) / 2 + 'px');
          } else {
            return element.css('left', 0);
          }
        };
        cover();
        return window.onresize = function() {
          return cover();
        };
      }
    };
  });
  app.directive('changeFont', function() {
    return {
      restrict: 'A',
      link: function(scope, element, attrs) {
        var fonts, i, task;
        fonts = ['cursive', '-webkit-body', '-webkit-pictograph', 'fantasy', 'serif'];
        i = 0;
        task = {};
        return $(element).hover(function() {
          var that, title;
          that = this;
          title = $('.navbar-brand');
          return task.now = setInterval($.proxy(function() {
            $(title).css('font-family', fonts[i]);
            $(that).css('font-family', fonts[i]);
            if (++i >= 5) {
              return i = 0;
            }
          }), 200);
        }, function() {
          return clearInterval(task.now);
        });
      }
    };
  });
  app.directive('drag', function() {
    return {
      restrict: 'EA',
      link: function(scope, element, attrs) {
        var moveDrag;
        element = $(element);
        moveDrag = function() {
          var X, Y, start;
          start = 0;
          X = 0;
          Y = 0;
          return element.mousedown(function(event) {
            console.log(X);
            start = 1;
            X = event.clientX;
            Y = event.clientY;
            $('body').mousemove(function(eve) {
              var theX;
              console.log('start2' + start);
              if (start) {
                theX = eve.clientX - X;
                X = eve.clientX;
                element.parent().css('left', '+=' + theX + 'px');
                $('.bk-left').css('width', '+=' + theX + 'px');
                return $('.bk-right').css('left', '+=' + theX + 'px');
              }
            });
            return $('body').mouseup(function() {
              if (start === 1) {
                start = 0;
                $('body').unbind('mousemove');
                return $('body').unbind('mouseup');
              }
            });
          });
        };
        return moveDrag();
      }
    };
  });
  app.directive('showDetail', function() {
    return {
      restrict: 'A',
      link: function(scope, element, attrs) {
        var $target;
        $target = $('.bk-' + attrs.showDetail);
        return $(element).hover(function() {
          if ($(window).width() > 768) {
            $target.addClass('active');
            return $('.round').not($(this)).addClass('fadeout');
          }
        }, function() {
          if ($(window).width() > 768) {
            $target.removeClass('active');
            return $('.round').not($(this)).removeClass('fadeout');
          }
        });
      }
    };
  });
  app.directive('vgGo', function() {
    return {
      restrict: 'A',
      link: function(scope, element, attrs) {
        return $(element).click(function() {
          return window.location.href = attrs.vgGo;
        });
      }
    };
  });
  return app.controller('mainCtrl', [
    '$scope', '$http', '$routeParams', '$rootScope', '$timeout', function($scope, $http, $routeParams, $rootScope, $timeout) {
      return $rootScope.$on('$routeChangeSuccess', function() {});
    }
  ]);
});

//# sourceMappingURL=main.js.map
